# Site settings
title: Seven Points
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - assets/scss
  - README.md

keep_files:
  - _site/css
  - _site/js

include: ['_pages']

